<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Dispatchly.DependencyInjection.Reflection/Dispatchly.DependencyInjection.Reflection.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>
</Project>
