<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Dispatchly</RootNamespace>
    <Description>Dispatcher and message catalog for Dispatchly.</Description>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dispatchly.Abstractions/Dispatchly.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Dispatchly.Core.Tests" />
    <InternalsVisibleTo Include="Dispatchly.DependencyInjection" />
  </ItemGroup>
</Project>
