using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Dispatchly.SourceGenerators;

internal static class SourceEmitter
{
    public static void Emit(SourceProductionContext source, IReadOnlyList<HandlerModel> models)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var valid = new List<HandlerModel>();
        foreach (var model in models.OrderBy(model => model.HandlerType, StringComparer.Ordinal).ThenBy(model => model.MessageType, StringComparer.Ordinal))
        {
            if (model.DiagnosticId is not null)
            {
                var descriptor = model.DiagnosticId == "DLY001" ? InvalidTable : UnsupportedMessage;
                source.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, model.MessageType, model.DiagnosticMessage));
                continue;
            }

            if (!seen.Add(model.HandlerType + "|" + model.MessageType))
            {
                continue;
            }

            valid.Add(model);
        }

        source.AddSource("DispatchlyGeneratedRegistration.g.cs", SourceText.From(Registration(valid), Encoding.UTF8));
        if (valid.Count > 0)
        {
            source.AddSource("DispatchlyJsonContext.g.cs", SourceText.From(JsonContext(valid), Encoding.UTF8));
        }
    }

    private static readonly DiagnosticDescriptor InvalidTable = new(
        "DLY001",
        "Invalid Dispatchly table name",
        "Dispatchly cannot register '{0}': {1}",
        "Dispatchly",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedMessage = new(
        "DLY002",
        "Unsupported Dispatchly message shape",
        "Dispatchly cannot register '{0}': {1}",
        "Dispatchly",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static string Registration(IReadOnlyList<HandlerModel> handlers)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Dispatchly.DependencyInjection");
        builder.AppendLine("{");
        builder.AppendLine("    public static class DispatchlyGeneratedRegistration");
        builder.AppendLine("    {");
        builder.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDispatchlyGeneratedHandlers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        builder.AppendLine("        {");
        builder.AppendLine("            AddDispatchlyGeneratedHandlers(global::Dispatchly.DependencyInjection.DispatchlyServiceCollectionExtensions.AddDispatchly(services));");
        builder.AppendLine("            return services;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static global::Dispatchly.DependencyInjection.DispatchlyBuilder AddDispatchlyGeneratedHandlers(this global::Dispatchly.DependencyInjection.DispatchlyBuilder builder)");
        builder.AppendLine("        {");
        var identifiers = MessageIdentifiers(handlers);
        foreach (var handler in handlers)
        {
            var identifier = identifiers[handler.MessageType];
            builder.AppendLine($"            builder.AddHandler<{handler.MessageType}, {handler.HandlerType}>(global::Dispatchly.Generated.DispatchlyJsonContext.Default.{identifier}, \"{handler.TableName}\");");
        }

        builder.AppendLine("            return builder;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string JsonContext(IReadOnlyList<HandlerModel> handlers)
    {
        var identifiers = MessageIdentifiers(handlers);
        var messages = handlers
            .GroupBy(handler => handler.MessageType, StringComparer.Ordinal)
            .Select(group => group.First())
            .ToArray();
        var primitives = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var message in messages)
        {
            for (var i = 0; i < message.Properties.Length; i++)
            {
                var property = message.Properties[i];
                primitives.Add(property.Kind + (property.IsNullable && property.Kind != "string" ? "?" : ""));
                if (property.IsNullable && property.Kind != "string")
                {
                    primitives.Add(property.Kind);
                }
                else if (property.Kind == "string")
                {
                    primitives.Add("string");
                }
            }
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Dispatchly.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal sealed class DispatchlyJsonContext : global::System.Text.Json.Serialization.JsonSerializerContext, global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver");
        builder.AppendLine("    {");
        builder.AppendLine("        private static readonly global::System.Text.Json.JsonSerializerOptions s_defaultOptions = new()");
        builder.AppendLine("        {");
        builder.AppendLine("            PropertyNamingPolicy = global::System.Text.Json.JsonNamingPolicy.CamelCase,");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("        public static DispatchlyJsonContext Default { get; } = new(new global::System.Text.Json.JsonSerializerOptions(s_defaultOptions));");
        builder.AppendLine();
        builder.AppendLine("        public DispatchlyJsonContext(global::System.Text.Json.JsonSerializerOptions options) : base(options) { }");
        builder.AppendLine();
        builder.AppendLine("        protected override global::System.Text.Json.JsonSerializerOptions? GeneratedSerializerOptions { get; } = s_defaultOptions;");
        builder.AppendLine();
        foreach (var message in messages)
        {
            var identifier = identifiers[message.MessageType];
            builder.AppendLine($"        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{message.MessageType}>? _{identifier};");
            builder.AppendLine($"        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{message.MessageType}> {identifier} => _{identifier} ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{message.MessageType}>)Options.GetTypeInfo(typeof({message.MessageType}))!;");
            builder.AppendLine();
        }

        builder.AppendLine("        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)");
        builder.AppendLine("        {");
        builder.AppendLine("            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);");
        builder.AppendLine("            return typeInfo;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)");
        builder.AppendLine("        {");
        foreach (var message in messages)
        {
            var identifier = identifiers[message.MessageType];
            builder.AppendLine($"            if (type == typeof({message.MessageType})) return Create_{identifier}(options);");
        }

        foreach (var primitive in primitives)
        {
            builder.AppendLine($"            if (type == typeof({ClrType(primitive)})) return CreatePrimitive_{PrimitiveMethod(primitive)}(options);");
        }

        builder.AppendLine("            return null;");
        builder.AppendLine("        }");

        foreach (var primitive in primitives)
        {
            AppendPrimitive(builder, primitive);
        }

        foreach (var message in messages)
        {
            AppendMessage(builder, message, identifiers[message.MessageType]);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendPrimitive(StringBuilder builder, string primitive)
    {
        var method = PrimitiveMethod(primitive);
        var clr = ClrType(primitive);
        builder.AppendLine();
        builder.AppendLine($"        private static global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{clr}> CreatePrimitive_{method}(global::System.Text.Json.JsonSerializerOptions options)");
        builder.AppendLine("        {");
        if (primitive.EndsWith("?", StringComparison.Ordinal))
        {
            var underlying = primitive.Substring(0, primitive.Length - 1);
            builder.AppendLine($"            return global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<{clr}>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GetNullableConverter<{ClrType(underlying)}>(options));");
        }
        else
        {
            builder.AppendLine($"            return global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<{clr}>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.{ConverterProperty(primitive)});");
        }

        builder.AppendLine("        }");
    }

    private static void AppendMessage(StringBuilder builder, HandlerModel message, string identifier)
    {
        builder.AppendLine();
        for (var i = 0; i < message.Properties.Length; i++)
        {
            var property = message.Properties[i];
            builder.AppendLine($"        private static readonly global::System.Text.Json.JsonEncodedText {property.EncodedField} = global::System.Text.Json.JsonEncodedText.Encode(\"{Escape(property.JsonName)}\");");
        }

        builder.AppendLine();
        builder.AppendLine($"        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<{message.MessageType}> Create_{identifier}(global::System.Text.Json.JsonSerializerOptions options)");
        builder.AppendLine("        {");
        builder.AppendLine($"            var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<{message.MessageType}>");
        builder.AppendLine("            {");
        if (message.ParameterizedConstructor)
        {
            builder.Append("                ObjectWithParameterizedConstructorCreator = static args => new ");
            builder.Append(message.MessageType);
            builder.Append('(');
            var parameterIndex = 0;
            for (var i = 0; i < message.Properties.Length; i++)
            {
                var property = message.Properties[i];
                if (!property.IsConstructorParameter)
                {
                    continue;
                }

                if (parameterIndex > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(Cast(property, parameterIndex));
                parameterIndex++;
            }

            builder.AppendLine("),");
        }
        else
        {
            builder.AppendLine($"                ObjectCreator = static () => new {message.MessageType}(),");
        }

        builder.AppendLine($"                PropertyMetadataInitializer = _ => {identifier}_Properties(options),");
        if (message.ParameterizedConstructor)
        {
            builder.AppendLine($"                ConstructorParameterMetadataInitializer = {identifier}_Parameters,");
        }

        builder.AppendLine($"                SerializeHandler = static (writer, value) => {identifier}_Write(writer, value),");
        builder.AppendLine("            };");
        builder.AppendLine($"            var info = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<{message.MessageType}>(options, objectInfo);");
        builder.AppendLine("            info.OriginatingResolver = this;");
        builder.AppendLine("            return info;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        private static void {identifier}_Write(global::System.Text.Json.Utf8JsonWriter writer, {message.MessageType}? value)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (value is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                writer.WriteNullValue();");
        builder.AppendLine("                return;");
        builder.AppendLine("            }");
        builder.AppendLine();
        builder.AppendLine("            writer.WriteStartObject();");
        for (var i = 0; i < message.Properties.Length; i++)
        {
            AppendWrite(builder, message.Properties[i]);
        }

        builder.AppendLine("            writer.WriteEndObject();");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] {identifier}_Properties(global::System.Text.Json.JsonSerializerOptions options)");
        builder.AppendLine("        {");
        builder.AppendLine($"            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[{message.Properties.Length}];");
        for (var i = 0; i < message.Properties.Length; i++)
        {
            AppendProperty(builder, message, message.Properties[i], i);
        }

        builder.AppendLine("            return properties;");
        builder.AppendLine("        }");

        if (message.ParameterizedConstructor)
        {
            builder.AppendLine();
            builder.AppendLine($"        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] {identifier}_Parameters() => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]");
            builder.AppendLine("        {");
            var position = 0;
            for (var i = 0; i < message.Properties.Length; i++)
            {
                var property = message.Properties[i];
                if (!property.IsConstructorParameter)
                {
                    continue;
                }

                builder.AppendLine("            new()");
                builder.AppendLine("            {");
                builder.AppendLine($"                Name = \"{property.Name}\",");
                builder.AppendLine($"                ParameterType = typeof({ClrType(property.Kind + (property.IsNullable && property.Kind != "string" ? "?" : ""))}),");
                builder.AppendLine($"                Position = {position},");
                builder.AppendLine("                HasDefaultValue = false,");
                builder.AppendLine("                DefaultValue = null,");
                builder.AppendLine($"                IsNullable = {(property.IsNullable ? "true" : "false")},");
                builder.AppendLine("            },");
                position++;
            }

            builder.AppendLine("        };");
        }
    }

    private static void AppendProperty(StringBuilder builder, HandlerModel message, PropertyModel property, int index)
    {
        var typeArgument = property.Kind == "string"
            ? "string"
            : ClrType(property.Kind + (property.IsNullable ? "?" : ""));
        var setter = property.HasSetter
            ? $"static (obj, value) => (({message.MessageType})obj).{property.Name} = value"
            : "static (obj, value) => throw new global::System.InvalidOperationException(\"Setting init-only properties is not supported.\")";
        builder.AppendLine($"            properties[{index}] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<{typeArgument}>(options, new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<{typeArgument}>");
        builder.AppendLine("            {");
        builder.AppendLine("                IsProperty = true,");
        builder.AppendLine("                IsPublic = true,");
        builder.AppendLine($"                DeclaringType = typeof({message.MessageType}),");
        builder.AppendLine($"                Getter = static obj => (({message.MessageType})obj).{property.Name},");
        builder.AppendLine($"                Setter = {setter},");
        builder.AppendLine($"                PropertyName = \"{property.Name}\",");
        builder.AppendLine($"                JsonPropertyName = \"{Escape(property.JsonName)}\",");
        builder.AppendLine("            });");
        builder.AppendLine($"            properties[{index}].IsGetNullable = {(property.IsNullable ? "true" : "false")};");
        builder.AppendLine($"            properties[{index}].IsSetNullable = {(property.IsNullable ? "true" : "false")};");
    }

    private static void AppendWrite(StringBuilder builder, PropertyModel property)
    {
        var access = $"value.{property.Name}";
        if (property.IsNullable)
        {
            builder.AppendLine($"            if ({access} is null)");
            builder.AppendLine("            {");
            builder.AppendLine($"                writer.WriteNull({property.EncodedField});");
            builder.AppendLine("            }");
            builder.AppendLine("            else");
            builder.AppendLine("            {");
            builder.AppendLine("                " + WriteValue(property.Kind, property.EncodedField, property.Kind == "string" ? access : access + ".Value"));
            builder.AppendLine("            }");
            return;
        }

        builder.AppendLine("            " + WriteValue(property.Kind, property.EncodedField, access));
    }

    private static string WriteValue(string kind, string encoded, string access) => kind switch
    {
        "string" or "char" or "guid" or "datetime" or "datetimeoffset" or "dateonly" or "timeonly" or "timespan" =>
            $"writer.WriteString({encoded}, {access});",
        "bool" => $"writer.WriteBoolean({encoded}, {access});",
        _ => $"writer.WriteNumber({encoded}, {access});",
    };

    private static string Cast(PropertyModel property, int index)
    {
        if (property.IsNullable)
        {
            return $"({property.TypeDisplay})args[{index}]";
        }

        return $"({property.TypeDisplay})args[{index}]!";
    }

    private static Dictionary<string, string> MessageIdentifiers(IReadOnlyList<HandlerModel> handlers)
    {
        var result = new Dictionary<string, string>(StringComparer.Ordinal);
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var handler in handlers.GroupBy(item => item.MessageType, StringComparer.Ordinal).Select(group => group.First()))
        {
            var identifier = handler.MessageIdentifier;
            var candidate = identifier;
            var suffix = 2;
            while (!used.Add(candidate))
            {
                candidate = identifier + suffix;
                suffix++;
            }

            result.Add(handler.MessageType, candidate);
        }

        return result;
    }

    private static string ClrType(string primitive) => primitive switch
    {
        "string" => "string",
        "bool" => "bool",
        "byte" => "byte",
        "short" => "short",
        "int" => "int",
        "long" => "long",
        "float" => "float",
        "double" => "double",
        "decimal" => "decimal",
        "char" => "char",
        "sbyte" => "sbyte",
        "ushort" => "ushort",
        "uint" => "uint",
        "ulong" => "ulong",
        "guid" => "global::System.Guid",
        "datetime" => "global::System.DateTime",
        "datetimeoffset" => "global::System.DateTimeOffset",
        "dateonly" => "global::System.DateOnly",
        "timeonly" => "global::System.TimeOnly",
        "timespan" => "global::System.TimeSpan",
        "bool?" => "bool?",
        "byte?" => "byte?",
        "short?" => "short?",
        "int?" => "int?",
        "long?" => "long?",
        "float?" => "float?",
        "double?" => "double?",
        "decimal?" => "decimal?",
        "char?" => "char?",
        "sbyte?" => "sbyte?",
        "ushort?" => "ushort?",
        "uint?" => "uint?",
        "ulong?" => "ulong?",
        "guid?" => "global::System.Guid?",
        "datetime?" => "global::System.DateTime?",
        "datetimeoffset?" => "global::System.DateTimeOffset?",
        "dateonly?" => "global::System.DateOnly?",
        "timeonly?" => "global::System.TimeOnly?",
        "timespan?" => "global::System.TimeSpan?",
        _ => throw new InvalidOperationException("Unsupported primitive " + primitive),
    };

    private static string PrimitiveMethod(string primitive) => primitive.Replace("?", "Nullable");

    private static string ConverterProperty(string primitive) => primitive switch
    {
        "string" => "StringConverter",
        "bool" => "BooleanConverter",
        "byte" => "ByteConverter",
        "short" => "Int16Converter",
        "int" => "Int32Converter",
        "long" => "Int64Converter",
        "float" => "SingleConverter",
        "double" => "DoubleConverter",
        "decimal" => "DecimalConverter",
        "char" => "CharConverter",
        "sbyte" => "SByteConverter",
        "ushort" => "UInt16Converter",
        "uint" => "UInt32Converter",
        "ulong" => "UInt64Converter",
        "guid" => "GuidConverter",
        "datetime" => "DateTimeConverter",
        "datetimeoffset" => "DateTimeOffsetConverter",
        "dateonly" => "DateOnlyConverter",
        "timeonly" => "TimeOnlyConverter",
        "timespan" => "TimeSpanConverter",
        _ => throw new InvalidOperationException("Unsupported primitive " + primitive),
    };

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
